README.md
main.cpp
mbed_app.json

First commit make application items configurable through mbed_app.json as oppose to previous use of macros in main.cpp.
Second commit provides documentation for the application.

Adding documentation and making items configurable through json

---

Jenkinsfile

* Run against mbed-os.lib, versions or PRs
* MTB Dragonfly added
* ARMC6 added
@AnttiKauppila please review

Support for running against mbed-os PRs

---

README.md
main.cpp
mbed-os.lib

mbed-os.lib changed to point to the latest version of the master, echo server changed, @adbridge @AnttiKauppila please review

lib and server update

---

README.md
main.cpp
mbed_app.json

Fixed forever loop if connection fails.
Fixed to set modem debug to correct place after settings the credentials so that is actually has an effect to modem debug.

Added trace support.

---

Jenkinsfile

* Added Ublox C030 to Jenkinsfile
* Removed target_families as looping through targets and toolchains is enough
Build results: https://jenkins-internal.mbed.com/job/ARMmbed/job/mbed-os-example-cellular/job/PR-66/ (5.8.x has a known issue, passes with master)
Test results: https://jenkins-internal.mbed.com/job/mbed-os-example-cellular-daily-hw-tester/ (C030 seems to have a connectivity issue which will be reported separately)

Add Ublox c030

---

Jenkinsfile

* Updated C027 Raas location
* Removed non-working tcp/udp list
* Added WISE-1570 and K64F-BG96 targets
* Changed configurations per target as dicussed
* Regression test results: https://jenkins-internal.mbed.com/job/mbed-os-example-cellular-daily-hw-tester/107/
* WISE-1570 and K64F-BG96 tested manually

Updated smoke test and added new targets

---

main.cpp
mbed_app.json

Brought out echo server to a configurable in mbed_app.json to easily change echo servers.

Configurable echo server

---

README.md
main.cpp
mbed_app.json

- updated readme, corrected links and simplified
- added disconnect
- added dot thread terminating as in some cases it was left runnin

Minor fixes, added disconnect and readme update.

---

Jenkinsfile

* C027 boards were moved under Ruka

Updated C027 RaaS location

---

README.md
mbed-os.lib

Updated mbed-os.lib to the latest mbed-os release commit hash.

Updated mbed-os.lib

---

main.cpp

To show the built date/time and default PLMN

---

README.md

Add link to os.mbed.com/docs, and fix broken links.

Add and update links to README.md

---

README.md
main.cpp

Added NonIP socket example

---

main.cpp

Use strlen for size of test payload instead of sizeof, which uses the pointer size, not the string length.

Use the actual length of the test string payload

---

Jenkinsfile

* Added NRF52840_DK + BG96 to Jenkinsfile
* Added workaround for mbed deploy issue in CI

NRF52840 to Jenkinsfile

---

Jenkinsfile

Checkout new PPP branch from mbed-os-cellular

Checkout branch from tiger1

---

Jenkinsfile

* Updated Raas location after infra changes
* Internal Jira ref: ISGTESTINF-4403

Raas location update

---

Jenkinsfile

* Added DISCO_L496AG to be compiled which uses STModCellular

Compile STMod Cellular

---

Jenkinsfile

Jenkinsfile: removed ublox c030 u201
- Target not supported anymore in master branch

Jenkinsfile: removed ublox c030 u201

---

CMakeLists.txt
gen_config/CMakeLists.txt
gen_config/mbed_config.h

CMake: Add support to build for WIO_3G

---

.travis.yml

- Added `.travis.yml` config to pick this example for Travis CI build
@hugueskamba @0xc0170 @paul-szczepanek-arm

CMake: Add Travis CI support

---

.travis.yml
mbed-os.lib

This pull request updates the example to be compatible with the 
mbed-os-6.6.0 release of mbed-os.

Update for mbed-os-6.6.0
